In [4]:
% matplotlib inline
% load_ext autoreload
% autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [10]:
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from torch.autograd import backward
from torch.optim import lr_scheduler, RMSprop,Adam
from torch.utils.data import Dataset, DataLoader

from spam_utils import *

In [11]:
corpus=Corpus()
model=Model(corpus,num_embeddings=None,embedding_dim=50,hidden_size=128,hidden_dim=64).cuda()
optimizer=Adam(model.parameters())
loss_fn=nn.BCELoss().cuda()

IndexError: too many indices for array

In [25]:
dataloaders={'train':DataLoader(SpamSet(True),batch_size=8,shuffle=True),
             'dev':DataLoader(SpamSet(False),batch_size=8,shuffle=False)}

In [28]:
fit(model, loss_fn, optimizer, dataloaders, {'accuracy': accuracy_score}, num_epochs=10, save=False)


N/A% (0 of 592) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--

  1% (8 of 592) |                        | Elapsed Time: 0:00:00 ETA:  00:00:00

  2% (15 of 592) |                       | Elapsed Time: 0:00:00 ETA:   0:00:05

Starting epoch 1 / 10
tensor([[2.1798e-11],
        [1.1674e-08],
        [2.4597e-08],
        [3.2356e-08],
        [1.9685e-08],
        [1.0441e-10],
        [7.0179e-08],
        [1.5113e-12]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], device='cuda:0')
tensor([[3.0073e-07],
        [3.1736e-07],
        [1.0000e+00],
        [1.6771e-06],
        [5.2383e-03],
        [1.9961e-05],
        [6.8459e-10],
        [3.9843e-09]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], device='cuda:0')
tensor([[7.4431e-13],
        [2.0994e-10],
        [1.6282e-08],
        [2.6862e-07],
        [3.5522e-04],
        [3.2284e-10],
        [9.2680e-06],
        [1.1679e-11]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [0.],
        [0.],

  3% (23 of 592) |                       | Elapsed Time: 0:00:00 ETA:   0:00:05

  5% (30 of 592) |#                      | Elapsed Time: 0:00:00 ETA:   0:00:05

  6% (38 of 592) |#                      | Elapsed Time: 0:00:00 ETA:   0:00:05

  7% (45 of 592) |#                      | Elapsed Time: 0:00:00 ETA:   0:00:04

tensor([[4.5494e-07],
        [3.4644e-11],
        [3.9876e-03],
        [3.4706e-12],
        [6.9612e-10],
        [1.0000e+00],
        [7.1817e-09],
        [1.0355e-02]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.]], device='cuda:0')
tensor([[1.2917e-10],
        [2.6675e-02],
        [1.0000e+00],
        [3.0347e-10],
        [9.3277e-05],
        [1.1661e-03],
        [1.1012e-06],
        [4.9114e-11]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], device='cuda:0')
tensor([[9.0852e-11],
        [1.0000e+00],
        [9.0234e-10],
        [8.0381e-12],
        [1.2286e-07],
        [1.8822e-04],
        [2.4820e-05],
        [1.6476e-08]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
       

  8% (53 of 592) |##                     | Elapsed Time: 0:00:00 ETA:   0:00:04

 10% (60 of 592) |##                     | Elapsed Time: 0:00:00 ETA:   0:00:04

 11% (68 of 592) |##                     | Elapsed Time: 0:00:00 ETA:   0:00:04

tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], device='cuda:0')
tensor([[1.0966e-02],
        [2.3171e-07],
        [7.1698e-02],
        [3.4924e-05],
        [2.4687e-07],
        [4.9036e-11],
        [8.1900e-06],
        [1.0000e+00]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.]], device='cuda:0')
tensor([[5.6295e-11],
        [1.7035e-05],
        [9.9079e-08],
        [9.9091e-05],
        [1.2940e-13],
        [1.0000e+00],
        [1.4502e-07],
        [4.5130e-12]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.]], device='cuda:0')
tensor([[6.5425e-10],
        [1.3579e-09],
        [1.3020e-11],
        [5.4147e-05],
        [2.2962e-05],
        [1.0000e+00],
        [1.4571e-05],
        [1.000

 12% (75 of 592) |##                     | Elapsed Time: 0:00:00 ETA:   0:00:04

 14% (83 of 592) |###                    | Elapsed Time: 0:00:00 ETA:   0:00:04

 15% (90 of 592) |###                    | Elapsed Time: 0:00:00 ETA:   0:00:04

 16% (98 of 592) |###                    | Elapsed Time: 0:00:00 ETA:   0:00:04

tensor([[4.9001e-03],
        [2.5782e-07],
        [4.1883e-04],
        [2.8087e-06],
        [9.9526e-08],
        [3.4845e-09],
        [2.9518e-11],
        [7.6976e-06]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], device='cuda:0')
tensor([[5.8025e-05],
        [8.0433e-06],
        [4.9359e-10],
        [5.5346e-03],
        [1.0000e+00],
        [6.8012e-05],
        [1.4734e-06],
        [1.2129e-06]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.]], device='cuda:0')
tensor([[6.6231e-05],
        [5.0697e-06],
        [2.7301e-03],
        [9.3275e-09],
        [3.2480e-07],
        [2.0988e-02],
        [4.5156e-07],
        [2.0675e-03]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
       

 17% (105 of 592) |###                   | Elapsed Time: 0:00:00 ETA:   0:00:03

 19% (113 of 592) |####                  | Elapsed Time: 0:00:00 ETA:   0:00:03

 20% (120 of 592) |####                  | Elapsed Time: 0:00:00 ETA:   0:00:03

tensor([[7.4599e-08],
        [1.0000e+00],
        [1.6189e-09],
        [4.4886e-12],
        [3.1848e-07],
        [2.5739e-07],
        [1.7218e-04],
        [8.8526e-05]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], device='cuda:0')
tensor([[1.3790e-09],
        [1.0000e+00],
        [1.0000e+00],
        [7.8104e-11],
        [8.1974e-10],
        [1.1236e-04],
        [4.0705e-09],
        [9.4202e-05]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], device='cuda:0')
tensor([[2.2028e-06],
        [3.6425e-08],
        [1.9288e-06],
        [9.2036e-07],
        [1.0000e+00],
        [7.7753e-08],
        [9.5946e-01],
        [7.4495e-05]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
       

 21% (128 of 592) |####                  | Elapsed Time: 0:00:01 ETA:   0:00:03

 22% (135 of 592) |#####                 | Elapsed Time: 0:00:01 ETA:   0:00:03

 24% (143 of 592) |#####                 | Elapsed Time: 0:00:01 ETA:   0:00:03

 25% (150 of 592) |#####                 | Elapsed Time: 0:00:01 ETA:   0:00:03

tensor([[4.2874e-04],
        [9.3416e-05],
        [3.4468e-02],
        [1.9016e-07],
        [4.0251e-09],
        [7.6730e-13],
        [2.4525e-03],
        [1.0000e+00]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.]], device='cuda:0')
tensor([[5.9937e-09],
        [7.3600e-08],
        [2.6281e-06],
        [1.2355e-05],
        [3.1225e-05],
        [2.9932e-02],
        [7.1401e-05],
        [3.1217e-09]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], device='cuda:0')
tensor([[2.9542e-10],
        [2.7612e-05],
        [1.0000e+00],
        [4.4602e-06],
        [3.0958e-02],
        [3.3436e-09],
        [2.3022e-10],
        [5.3606e-08]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [1.],
        [0.],
        [0.],
       

 26% (158 of 592) |#####                 | Elapsed Time: 0:00:01 ETA:   0:00:03

tensor([[5.1072e-10],
        [2.7641e-08],
        [1.2598e-08],
        [4.8311e-14],
        [1.1333e-12],
        [2.3415e-04],
        [8.8512e-07],
        [3.7480e-04]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], device='cuda:0')
tensor([[1.0056e-05],
        [8.1044e-08],
        [1.9828e-09],
        [1.0000e+00],
        [2.4684e-09],
        [9.8593e-06],
        [1.0000e+00],
        [4.7673e-04]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.]], device='cuda:0')
tensor([[6.0101e-08],
        [1.0000e+00],
        [2.1848e-08],
        [4.1213e-06],
        [9.2436e-10],
        [7.6075e-09],
        [2.9644e-08],
        [2.3710e-06]], device='cuda:0', grad_fn=<SigmoidBackward>) tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
       

KeyboardInterrupt: 